name: "build"

on:
  push:
  pull_request:

jobs:
  build:
    name: Build on ${{ matrix.os }} with ${{ matrix.comp }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-latest, comp: "gcc", gcc-version: 14 }
          - { os: windows-latest, comp: "msvc" }
    #           - { os: macos-latest, comp: 'clang@llvm-19' }  # disable macos for now since it seems to hang

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: install gcc ${{ matrix.gcc-version }}
        if: matrix.comp == 'gcc'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-${{ matrix.gcc-version }} g++-${{ matrix.gcc-version }}

      - name: install linux deps
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libxcb1-dev libxcb-xtest0-dev

      - name: setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          # actions-cache-folder: '.xmake-cache'
          # actions-cache-key: 'xmake-2137'
          # package-cache: true
          # package-cache-key: 'xmake-2137'  # NOTE: edit this key to invalidate caches
          # build-cache: true
          # build-cache-key: 'xmake-${{ matrix.os }}-${{ matrix.comp }}'

      - name: Set compiler environment
        shell: bash
        run: |
          if [ "${{ matrix.comp }}" = "gcc" ]; then
            echo "CC=gcc-${{ matrix.gcc-version }}" >> $GITHUB_ENV
            echo "CXX=g++-${{ matrix.gcc-version }}" >> $GITHUB_ENV
          elif [ "${{ matrix.comp }}" = "clang" ]; then
            echo "CC=clang-${{ matrix.clang-version }}" >> $GITHUB_ENV
            echo "CXX=clang++-${{ matrix.clang-version }}" >> $GITHUB_ENV
            echo "LD=lld-${{ matrix.clang-version }}" >> $GITHUB_ENV
          fi

      - name: build
        run: |
          xmake repo -u
          xmake f --yes -m release --toolchain=${{ matrix.comp }}
          xmake pack

      - uses: actions/upload-artifact@v4
        with:
          name: kadr_${{ matrix.os }}_${{ matrix.comp }}
          path: |
            ${{ github.workspace }}/build/xpack/kadr
          if-no-files-found: warn
